bases:
  - github.com/binkhq/azureblob-to-azureblob/deploy


patches:
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env
        value:
          - name: SRC_CONN_STR
            valueFrom:
              secretKeyRef:
                key: source_connection_string
                name: azure-storage-common
          - name: DST_CONN_STR
            valueFrom:
              secretKeyRef:
                key: dest_connection_string
                name: azure-storage-common
          - name: SRC_CON_NAME
            value: media
          - name: DST_CON_NAME
            value: blob-container-02