bases:
  - github.com/binkhq/azureblob-to-azureblob/deploy


patches:
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env
        value:
          - name: source_connection_string
            valueFrom:
              secretKeyRef:
                key: connection_string
                name: azure-storage-common
          - name: destination_connection_string
            valueFrom:
              secretKeyRef:
                key: connection_string
                name: azure-storage-common
          - name: source_container_name
            value: media
          - name: destination_container_name
            value: backups
