name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install poetry==1.2.0b3
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: black --line-length=120 --check .
  build:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: build
    runs-on: ubuntu-latest
    needs: [ tests ]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - run: echo "::set-output name=date::$(date +'%FT%H%M%SZ')"
      id: date
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/binkhq/azureblob-to-azureblob:${{ steps.date.outputs.date }}
          ghcr.io/binkhq/azureblob-to-azureblob:latest
